server:
  port: 6232
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///aigou-product?userUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
